version: 1
disable_existing_loggers: True

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: ERROR
        formatter: standard
        filename: logs/info.log

loggers:
    api.server_api:
        level: DEBUG
        handlers: [file, console]
        propogate: False
    api.model_api:
        level: DEBUG
        handlers: [file, console]
        propogate: False
    src.model.yamnet:
        level: DEBUG
        handlers: [file, console]
        propogate: False
    src.preprocess:
        level: DEBUG
        handlers: [file, console]
        propogate: False
    src.utilities.system:
        level: DEBUG
        handlers: [file]
        propogate: False
    src.scraping.drive:
        level: DEBUG
        handlers: [file, console]
        propogate: False
    src.preprocessing.audio:
        level: DEBUG
        handlers: [file]
        propogate: False
    src.preprocessing.datafilter:
        level: DEBUG
        handlers: [file]
        propogate: False
    src.preprocessing.feature:
        level: DEBUG
        handlers: [file]
        propogate: False
    src.preprocessing.graph:
        level: DEBUG
        handlers: [file]
        propogate: False        
    src.utilities.view:
        level: DEBUG
        handlers: [file]
        propogate: False
    src.utilities.prepare:
        level: DEBUG
        handlers: [file]
        propogate: False

root:
    level: DEBUG
    handlers: [console, file]